### ISSUE TITLE
Manage secrets with dotenv

### ISSUE THREAD

**Issue by Kavignon** [Elixir-journey/elixir-kickoff#10]
Add support for managing secrets with .env files and load them into the project as needed.

## Tasks

- [ ] Set up dotenv for environment variables.
- [ ] Update .gitignore to ignore .env files.
- [ ] Document how to use .env files in the README.
