### ISSUE TITLE
Enable documentation with ExDoc

### ISSUE THREAD

**Issue by Kavignon** [Elixir-journey/elixir-kickoff#11]
Integrate ExDoc for generating project documentation.

## Tasks

- [ ] Install and configure ExDoc in the project.
- [ ] Add instructions in the README for generating documentation.
- [ ] Set up a GitHub Pages action to host documentation (optional).
