### ISSUE TITLE
Add support for ZSH terminal preference in devcontainer

### ISSUE THREAD

**Issue by Kavignon** [Elixir-journey/elixir-kickoff#19]
## Description

So while using the dev container, I want to be able to use my preferences in terms of Terminal setup so it doesn't feel like I'm moving backwards when using the the remote container on my local machine. So, the kickoff template should allow users to bring their own configurations (ex: .zshrc along with their themes) without feeling limited by the tooling. This should improve the developer experience and consistency with local environments.

## Tasks  
- [ ] Detect the user configuration from their local environment (are they using .zshrcfor instance).
- [ ] Copy the user's configuration in the host's directory in the devcontainer's home directory.
- [ ]  Set the container's default shell based on the user's preference.
- [ ] Ensure the custom configurations load correctly within the dev container's terminal.
- [ ] Extend the pre-built container for supporting ZSH configuration.
