### ISSUE TITLE
Add devcontainer support

### ISSUE THREAD

**Issue by Kavignon** [Elixir-journey/elixir-kickoff#3]
Add a .devcontainer folder with devcontainer.json for a consistent development environment in VS Code.

## Tasks

- [x] Create .devcontainer/devcontainer.json with basic settings.
- [x] Define extensions and settings for Elixir development.
- [x] Document usage in the README.
