### ISSUE TITLE
Provide support for multiple Elixir/OTP versions

### ISSUE THREAD

**Issue by Kavignon** [Elixir-journey/elixir-kickoff#43]
# Description

Extending the CI workflow to support multiple versions of Elixir and OTP ensures compatibility across various environments. This is crucial for libraries or HEX modules, which may be used in projects running on different Elixir/OTP versions. By adding a build matrix, we can test combinations of Elixir and OTP versions to detect compatibility issues early.

## Tasks 
- [x] Investigate using a build matrix in GitHub Actions to test combinations of Elixir and OTP versions.
- [x] Configure the build matrix to include the following Elixir versions: 1.14, 1.15, 1.16 & 1.17.
- [x] Configure the build matrix to include the following OTP versions: 24, 25, 26 & 27.
- [x] Update the CI workflow to run tests for each combination in the matrix.

**Comment by Kavignon** [comment]
Example of Action run: https://github.com/Elixir-journey/elixir-kickoff/actions/runs/12226200772
