### ISSUE TITLE
Add ExUnit support for testing

### ISSUE THREAD

**Issue by Kavignon** [Elixir-journey/elixir-kickoff#5]
Set up ExUnit as the default testing framework and include example tests.

## Tasks

- [ ] Configure ExUnit in the project.
- [ ] Add a sample test file for demonstration.
- [ ] Document how to run tests in the README.

**Comment by Kavignon** [comment]
It is part of Elixir’s standard library, comes pre-installed, and is available in all Elixir projects by default. So this is a void issue.
